preferences:
  general:
    audioLib: sounddevice
    units: deg


window:
    size: [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True
    screen: 0
    viewPos: [0.0,0.0]

monitor:
    name: default
    width: 69.8  # in cm
    distance: 196  # in cm
    # gamma: 2.1 # activate this setting for BOLD screen!
    gamma: 1


mouse:
  visible: False

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    active_eye: left  # [right]
    binocular_enabled: NO  # [YES]
    heuristic_filter: 2  # [0, OFF, 1, ON]
    pupil_size_diameter: YES  # [NO]
    #simulate_head_camera: NO  # [YES]  # GIVES ERROR?
    #simulation_screen_distance
    file_event_filter: 'LEFT,RIGHT,FIXATION,SACCADE,BLINK,MESSAGE,BUTTON,INPUT'
    link_event_filter: 'LEFT,RIGHT,FIXATION,SACCADE,BLINK,BUTTON'
    link_sample_data: 'LEFT,RIGHT,GAZE,GAZERES,AREA,STATUS,HTARGET'
    #file_sample_data: LEFT,RIGHT,GAZE,AREA,GAZERES,STATUS,HTARGET,INPUT'  # GIVES ERROR?
    calibration_type: HV9  # [H3, HV3, HV5, HV9]
    x_gaze_constraint: AUTO
    y_gaze_constraint: AUTO
    enable_automatic_calibration: YES  # [NO]
    automatic_calibration_pacing: 1000
    enable_search_limits: YES
    track_search_limits: YES
    autothreshold_click: YES
    autothreshold_repeat: YES
    enable_camera_position_detect: YES
    sample_rate: 1000

mri:
  simulate: False
  # TR: 1.5 #1.32  # seconds between volume acquisitions
  TR: 1.6 #1.32  # seconds between volume acquisitions
  # TA: 1.32  # seconds to acquire one volume
  volumes: 160  # number of 3D volumes to obtain in a given scanning run
  sync: t  # character used as flag for sync timing, default=‘5’
  skip: 4  # how many frames to silently omit initially during T1 stabilization, no sync pulse.
  sound: False  # simulate scanner noise
  topup_scan: True
  topup_duration: 30 #45 # topup scan duration in seconds (no 't's)

# times in frames based on 120 FPS screen
stimuli:
    tex_type: 'snakes-new'                     # either of ['rms', 'minmax'], determines the rescaling used
    snake_density: 4
    scanner_sync: True                 # set this to true to make phase p0 (prep) end on input 't', overrides default TR/2
    #screenshot: True                   # TODO implement
    blank_before_trs: 11                # how many TRs of blank before the task starts properly; 13*TR = 17.16s
    blank_after_trs: 15                 # how many TRs of blank after the task has finished; 18*TR = 23.76s
    # stimulus offsets to correct for bold screen
    x_offset: 0.0 # pos r, neg l
    y_offset: -1.0 # pos up, neg down
    ## block settings
    flicker_speed: 134 # 330, 660 [ms]
    # block_on_length_TR: 9 # [n_TR] of a given on or off block 2D EPI
    # block_off_length_TR: 9 # [n_TR] of a given on or off block 2D EPI
    # block_off_length_s: 9 # [n_TR] of a given on or off block 2D EPI
    
    ## change sequence and duration accordingly here
    # iti_sequence: [12, 11, 13, 13, 11, 14, 14, 15, 12, 15]
    # iti_sequence: [14, 11, 13, 15, 12, 12, 13, 15, 14, 11]
    # iti_sequence: [14, 11, 14, 13, 15, 13, 12, 11, 15, 12]
    iti_sequence: [12, 12, 11, 15, 11, 14, 15, 13, 14, 13]
    stim_duration: 1.5 # stimulus duration in s 


# times in seconds
task: 
    response interval: 0.8             # time in s you allow the participant to respond that still counts as correct response
    color switch interval: 5 #3.5         # interval in s between color dot switches, note: a random decimal between -1 and +1 is added to it in the code 
    fix_dot_size: .5                 # fixation dot size in degrees. Dot changes color on average every two TRs (or bar steps)
    fix_dot_colors: ['green', 'red']   # fixation dot colors
